runtime: custom
env: flex
entrypoint: dotnet CurrencyConverter.dll

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 10
